<a href="https://colab.research.google.com/github/Nkoushik30/ML-workshop/blob/main/Assingnment(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  numpy Assignment(1)

importing numpy package

In [ ]:
import numpy as np

Q1. Perform arithmetic operations on NumPy arrays.

In [ ]:
arr1=np.array([3,2,5,6,7])
arr2=np.array([5,3,4,7,9])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr1//arr2)
print(arr1%arr2)

[ 8  5  9 13 16]
[-2 -1  1 -1 -2]
[15  6 20 42 63]
[0.6        0.66666667 1.25       0.85714286 0.77777778]
[0 0 1 0 0]
[3 2 1 6 7]


Q2. Write a script to compute the mean and standard deviation of a NumPy array.

In [ ]:
arr3=np.array([6,14,12,3,8,6,9,4])
p=np.std(arr3)
s=np.mean(arr3)
print("Mean value of arr3:",s)
print("standed deviation value of arr3:",p)

Mean value of arr3: 7.75
standed deviation value of arr3: 3.5619517121937516


Q3. Create a NumPy array of integers from 10 to 50 with a step size of 5.

In [ ]:
arr4=np.arange(10,51,5)
print(arr4)

[10 15 20 25 30 35 40 45 50]


Q4. Reshape the array into a 2x4 matrix.

In [ ]:
arr5=np.array([1,5,3,6,9,4,2,3])
s=arr5.reshape(2,4)
print(s)

[[1 5 3 6]
 [9 4 2 3]]


Q5. Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):
       
        • Extract the sub-matrix containing the last two rows and first two columns.
        • Replace all elements greater than 4 with 0.

In [ ]:
arr6=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
s1=arr6[1:,:2]
print(s1)

[[4 5]
 [7 8]]


In [ ]:
arr6[arr6>4]=0
print(arr6)

[[1 2 3]
 [4 0 0]
 [0 0 0]]


Q6. Create two 1D arrays:

      • a = np.array([1, 2, 3])
      • b = np.array([4, 5, 6])
      • Perform element-wise addition, multiplication, and division

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("adition of arrays a,b:",a+b)
print("subtraction of arrays a,b:",a-b)
print("multiplication of arrays a,b:",a*b)
print("division of arrays a,b:",a/b)

adition of arrays a,b: [5 7 9]
subtraction of arrays a,b: [-3 -3 -3]
multiplication of arrays a,b: [ 4 10 18]
division of arrays a,b: [0.25 0.4  0.5 ]


Q7. Create a random NumPy array of size (4, 4). Compute:

      • Mean of each column.
      • Maximum value of the entire array.
      • Sum of all elements.

In [ ]:
arr7=np.random.randint(0,100,(4,4))
s1=np.mean(arr7,axis=0)
s2=np.max(arr7)
s3=np.sum(arr7)
print(s1)
print(s2)
print(s3)

[62.  32.  55.5 33.5]
95
732


8. Given the array arr = np.array([1, 2, 3, 4]),add 10 to each element and multiply the result by 2.

In [ ]:
arr8=np.array([1, 2, 3, 4])
s1=arr8*10
s2=s1*2
print(s2)

[20 40 60 80]


9. Perform advanced slicing and indexing on a 3D array.
Create a 3D NumPy array arr of shape (3, 4, 5) with random integers ranging from
1 to 100. Perform the following:


      • Extract the second "layer" (i.e., the second 2D array) in the first dimension.
      • Extract the first two rows and the last three columns from each "layer."
      • Replace all elements divisible by 3 with -1.


In [ ]:
arr9=np.random.randint(1,100,(3,4,5))
s1=np.array(arr9[1])
s2=np.array(arr9[1,:2,-3:])
print(arr9)
print(s2)
print(s1)

[[[84 13 58 56 50]
  [51 88 80 38 75]
  [72 91 88 41 60]
  [10 26 34 54 84]]

 [[81 44 44 41 14]
  [19 59 80 71 85]
  [61 45 43 18 45]
  [36 38 46 24 16]]

 [[36 23 27  8 39]
  [90 64 21 95 38]
  [36 10 87 98 45]
  [93 93 91 29 29]]]
[[44 41 14]
 [80 71 85]]
[[81 44 44 41 14]
 [19 59 80 71 85]
 [61 45 43 18 45]
 [36 38 46 24 16]]


In [ ]:
arr9[arr9%3==0]=-1
print(arr9)

[[[-1 13 58 56 50]
  [-1 88 80 38 -1]
  [-1 91 88 41 -1]
  [10 26 34 -1 -1]]

 [[-1 44 44 41 14]
  [19 59 80 71 85]
  [61 -1 43 -1 -1]
  [-1 38 46 -1 16]]

 [[-1 23 -1  8 -1]
  [-1 64 -1 95 38]
  [-1 10 -1 98 -1]
  [-1 -1 91 29 29]]]


10. Work with broadcasting and advanced operations in NumPy.
 Create a NumPy array arr of shape (3, 3) with random integers between
 1 and 20. Perform the following:


      • Subtract the mean of each row from its respective elements (row-wise
      normalization).
      • Create a new array by squaring all the elements in arr.
      • Find the indices of the top 3 maximum values in the entire array.

In [ ]:
arr10=np.random.randint(1,20,(3,3))
s1=arr10-arr10.mean(axis=1,keepdims=True)
print(s1)
s2=np.square(arr10)
print(s2)

[[ 6.         -4.         -2.        ]
 [ 1.33333333 -1.66666667  0.33333333]
 [-6.33333333  9.66666667 -3.33333333]]
[[169   9  25]
 [ 16   1   9]
 [  1 289  16]]
